# Numpy 配列

In [1]:
import numpy as np
matrix = np.array([
    [11, 12, 13],
    [21, 22, 23],
    [31, 32, 33]
])
matrix

array([[11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

# 疎行列
0が多数の行列を効率的に処理する

In [2]:
import  numpy as np
from scipy import sparse

matrix = np.array([
    [0, 0],
    [0, 1],
    [3, 0]
])
matrix_aparse = sparse.csr_matrix(matrix)
print(matrix_aparse)

  (1, 1)	1
  (2, 0)	3


# 行列要素の選択

In [3]:
import numpy as np
matrix = np.array([
    [11, 12, 13],
    [21, 22, 23],
    [31, 32, 33]
])
matrix[2]

array([31, 32, 33])

# 行列の情報を取得する

In [4]:
import numpy as np
matrix = np.array([
    [11, 12, 13],
    [21, 22, 23],
    [31, 32, 33]
])

# 行, 列
print(matrix.shape)
# 要素数
print(matrix.size)
# 次元数
print(matrix.ndim)


(3, 3)
9
2


# 行列の計算

In [5]:
import numpy as np
matrix = np.array([
    [11, 12, 13],
    [21, 22, 23],
    [31, 32, 33]
])

# 画像を0~1の間に変換する処理はよく使う
matrix / 255

array([[0.04313725, 0.04705882, 0.05098039],
       [0.08235294, 0.08627451, 0.09019608],
       [0.12156863, 0.1254902 , 0.12941176]])

# 最小値、最大値、平均値、分散、標準偏差

In [6]:
import numpy as np
matrix = np.array([
    [11, 12, 13],
    [21, 22, 23],
    [31, 32, 33]
])

# 最小値
print(np.min(matrix))
# 最大値
print(np.max(matrix))
# 列単位 ↓
print(np.max(matrix, axis=0))
# 行単位 →
print(np.max(matrix, axis=1))
# 平均値
print(np.mean(matrix))
# 分散
print(np.var(matrix))
# 標準偏差
print(np.std(matrix))


11
33
[31 32 33]
[13 23 33]
22.0
67.33333333333333
8.205689083394114


# 配列の形状変換

In [7]:
import numpy as np
matrix = np.array([
    [11, 12, 13],
    [21, 22, 23],
    [31, 32, 33]
])

# 画像認識などで利用する
matrix = matrix.reshape(3, 3, 1)
print(matrix.shape)
print(matrix)

# -1を指定した場合自動で推測される 元の形状と互換性を保つ必要がある。この場合だと(2, -1)などは指定できない
matrix = matrix.reshape(3, -1)
print(matrix.shape)
print(matrix)


(3, 3, 1)
[[[11]
  [12]
  [13]]

 [[21]
  [22]
  [23]]

 [[31]
  [32]
  [33]]]
(3, 3)
[[11 12 13]
 [21 22 23]
 [31 32 33]]


# 行列の転置

In [8]:
import numpy as np
matrix = np.array([
    [11, 12, 13],
    [21, 22, 23],
    [31, 32, 33]
])

# 環境、ライブラリによっては行列が逆転している場合がある
matrix.T

array([[11, 21, 31],
       [12, 22, 32],
       [13, 23, 33]])

# 行列のフラット化

In [9]:
import numpy as np
matrix = np.array([
    [11, 12, 13],
    [21, 22, 23],
    [31, 32, 33]
])

print(matrix.flatten())

matrix = np.array([
    [11, 12, 13],
    [21, 22, 23],
    [31, 32, 33]
])
# 以下とほぼ同じ挙動になる
print(matrix.reshape(1, -1))

[11 12 13 21 22 23 31 32 33]
[[11 12 13 21 22 23 31 32 33]]


# 乱数のseed値設定、乱数生成

In [10]:
import numpy as np

# 再現可能にするためにseed値を設定する
np.random.seed(666)

# 乱数を10個生成
np.random.random(10)

array([0.70043712, 0.84418664, 0.67651434, 0.72785806, 0.95145796,
       0.0127032 , 0.4135877 , 0.04881279, 0.09992856, 0.50806631])